[2024-11-25 16:01:50,869] INFO [GroupCoordinator 0]: Member consumer-test-group-2-1-66ce2032-41b1-4e95-b39e-75115a0c9646 in group test-group-2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:01:50,869] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 459 (__consumer_offsets-37) (reason: removing member consumer-test-group-2-1-66ce2032-41b1-4e95-b39e-75115a0c9646 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:01:52,727] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 460 (__consumer_offsets-37) with 2 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:01:52,728] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 460. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:02:08,926] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group test-group-2 in Stable state. Created a new member id consumer-test-group-2-1-19c09631-2dbf-4b58-81aa-0b91bfbd87fa and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:02:09,001] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 460 (__consumer_offsets-37) (reason: Adding new member consumer-test-group-2-1-19c09631-2dbf-4b58-81aa-0b91bfbd87fa with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:02:10,870] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 461 (__consumer_offsets-37) with 3 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:02:10,870] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 461. The group has 3 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:03:02,693] INFO [GroupCoordinator 0]: Member consumer-test-group-2-1-19c09631-2dbf-4b58-81aa-0b91bfbd87fa in group test-group-2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:03:02,693] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 461 (__consumer_offsets-37) (reason: removing member consumer-test-group-2-1-19c09631-2dbf-4b58-81aa-0b91bfbd87fa on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:03:05,014] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 462 (__consumer_offsets-37) with 2 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:03:05,015] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 462. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:06:52,363] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 218762506 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:52,447] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:52,519] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1330664521 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:52,602] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1330664521 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:52,719] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = -2147483608)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:103)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:55,892] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1212501072 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:55,966] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295360 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,611] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295360 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,688] ERROR Closing socket for 74.208.112.63:9092-142.93.192.95:56740-222 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: 27265
Caused by: java.lang.IllegalArgumentException: Unexpected api key: 27265
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:186)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:93)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,689] ERROR Exception while processing request from 74.208.112.63:9092-142.93.192.95:56740-222 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: 27265
Caused by: java.lang.IllegalArgumentException: Unexpected api key: 27265
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:186)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:93)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,775] ERROR Closing socket for 74.208.112.63:9092-142.93.192.95:56742-222 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: -173
Caused by: java.lang.IllegalArgumentException: Unexpected api key: -173
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:186)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:93)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,775] ERROR Exception while processing request from 74.208.112.63:9092-142.93.192.95:56742-222 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: -173
Caused by: java.lang.IllegalArgumentException: Unexpected api key: -173
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:186)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:93)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,860] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1811942144 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:57,939] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:59,676] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 813957120 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:06:59,875] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 806093313 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:00,007] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1330664521 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:00,334] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1414417744 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:02,369] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1148019796 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:02,639] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 973078528 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:02,784] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1246907721 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:06,387] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 302055476 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:08,713] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195986768 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:11,112] WARN [SocketServer listenerType=ZK_BROKER, nodeId=0] Unexpected error from /142.93.192.95; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 268436224 larger than 104857600)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:989)
	at kafka.network.Processor.run(SocketServer.scala:892)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:13,100] ERROR Closing socket for 74.208.112.63:9092-142.93.192.95:45824-229 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: -1
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:651)
	at java.base/java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:350)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:91)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:13,101] ERROR Exception while processing request from 74.208.112.63:9092-142.93.192.95:45824-229 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: -1
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:651)
	at java.base/java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:350)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:91)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:18,365] ERROR Closing socket for 74.208.112.63:9092-142.93.192.95:52588-230 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: -1
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:651)
	at java.base/java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:350)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:91)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:07:18,365] ERROR Exception while processing request from 74.208.112.63:9092-142.93.192.95:52588-230 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error parsing request header. Our best guess of the apiKey is: -1
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:651)
	at java.base/java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:350)
	at org.apache.kafka.common.requests.RequestHeader.parse(RequestHeader.java:91)
	at kafka.network.Processor.parseRequestHeader(SocketServer.scala:999)
	at kafka.network.Processor.$anonfun$processCompletedReceives$1(SocketServer.scala:1012)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at kafka.network.Processor.processCompletedReceives(SocketServer.scala:1008)
	at kafka.network.Processor.run(SocketServer.scala:893)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-25 16:18:21,676] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group test-group-2 in Stable state. Created a new member id consumer-test-group-2-1-8329d658-7f43-4f36-8936-3d39fae7df91 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:18:21,750] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 462 (__consumer_offsets-37) (reason: Adding new member consumer-test-group-2-1-8329d658-7f43-4f36-8936-3d39fae7df91 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:18:23,242] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 463 (__consumer_offsets-37) with 3 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:18:23,242] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 463. The group has 3 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:19:18,451] INFO [GroupCoordinator 0]: Member consumer-test-group-2-1-8329d658-7f43-4f36-8936-3d39fae7df91 in group test-group-2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:19:18,451] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 463 (__consumer_offsets-37) (reason: removing member consumer-test-group-2-1-8329d658-7f43-4f36-8936-3d39fae7df91 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:19:20,384] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 464 (__consumer_offsets-37) with 2 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:19:20,385] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 464. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:35:44,209] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group test-group-2 in Stable state. Created a new member id consumer-test-group-2-1-a5da65e2-977d-4d7c-b5a5-d68d2db1101e and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:35:44,281] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 464 (__consumer_offsets-37) (reason: Adding new member consumer-test-group-2-1-a5da65e2-977d-4d7c-b5a5-d68d2db1101e with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:35:44,594] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 465 (__consumer_offsets-37) with 3 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:35:44,595] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 465. The group has 3 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:37:33,953] INFO [GroupCoordinator 0]: Member consumer-test-group-2-1-a5da65e2-977d-4d7c-b5a5-d68d2db1101e in group test-group-2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:37:33,953] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 465 (__consumer_offsets-37) (reason: removing member consumer-test-group-2-1-a5da65e2-977d-4d7c-b5a5-d68d2db1101e on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:37:35,741] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 466 (__consumer_offsets-37) with 2 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:37:35,741] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 466. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:53:09,126] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group test-group-2 in Stable state. Created a new member id consumer-test-group-2-1-95d5b0e7-9f90-4c96-ae11-bc10f906fc5a and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:53:09,200] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 466 (__consumer_offsets-37) (reason: Adding new member consumer-test-group-2-1-95d5b0e7-9f90-4c96-ae11-bc10f906fc5a with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:53:11,957] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 467 (__consumer_offsets-37) with 3 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:53:11,957] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 467. The group has 3 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:55:22,327] INFO [GroupCoordinator 0]: Member consumer-test-group-2-1-95d5b0e7-9f90-4c96-ae11-bc10f906fc5a in group test-group-2 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:55:22,327] INFO [GroupCoordinator 0]: Preparing to rebalance group test-group-2 in state PreparingRebalance with old generation 467 (__consumer_offsets-37) (reason: removing member consumer-test-group-2-1-95d5b0e7-9f90-4c96-ae11-bc10f906fc5a on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:55:24,107] INFO [GroupCoordinator 0]: Stabilized group test-group-2 generation 468 (__consumer_offsets-37) with 2 members (kafka.coordinator.group.GroupCoordinator)
[2024-11-25 16:55:24,108] INFO [GroupCoordinator 0]: Assignment received from leader consumer-test-group-2-1-1c74320d-3e7c-45f7-8525-bd9cbeaccf34 for group test-group-2 for generation 468. The group has 2 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
